services:
  # Single Web Service - Backend + Frontend
  - type: web
    name: wholetail-app
    env: node
    rootDir: wholetail-backend
    buildCommand: npm install && cd ../wholetail-frontend && npm install && npm run build && cp -r build ../wholetail-backend/public
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
    branch: main
